name: CI/CD Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: # Importante para o robô conseguir comentar no seu código
      contents: read
      pull-requests: write
      checks: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and Test with Maven
        run: mvn clean verify


      - name: Checkstyle Report (Annotations)
        uses: dbelyaev/action-checkstyle@master
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          checkstyle_xml: target/checkstyle-result.xml
          level: warning


      - name: JaCoCo Report
        uses: madrapps/jacoco-report@v1.6.1
        if: always()
        with:
          paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40